name: game_of_life_dart
version: 0.0.0
description: Extended Conway's Game of Live as a terminal based application. Makes heavy use of Unicode symbols for boxes and grid. Multiple zoom levels.
repository: https://github.com/centaurus22/game-of-life-dart

environment:
  sdk: ^3.9.3

dependencies:
  dart_console: ^4.1.2

dev_dependencies:
  build_runner: ^2.8.0
  coverage: ^1.15.0
  lints: ^6.0.0
  mockito: ^5.5.1
  test: ^1.25.6

platforms:
  linux:

funding: https://www.paypal.com/paypalme/klausthorres

topics:
  - simulation
  - tui
  - text
  - unicode
  - clean-architecture